### ISSUE TITLE
Help Desk API: Small Typo

### ISSUE THREAD

**Issue by michaelmaw** [spiceworks/spiceworks-js-sdk#2]
Just a small typo on the Help Desk API for retrieving a single ticket...

https://github.com/spiceworks/spiceworks-js-sdk/blob/master/docs/apis/helpdesk.md

--> card.services('helpdesk').request('tickets', id)

'tickets' should be 'ticket' (no "s")

**Comment by msgerbush** [comment]
Doh, nice catch! :+1:
